/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.problem_1;

import static com.mycompany.problem_1.BT.root;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dell
 */
public class DrawArea extends javax.swing.JFrame {

    String s;


    /**
     * Creates new form DrawArea
     */

    public DrawArea() {
        initComponents();
    }

    public DrawArea(String s) {
        initComponents();
        
        int totalWidth = BT.totalWidth(root);
        try {
            String str = BT.export_from_tree_to_rectangle(root,"mainTree.txt");
            if(totalWidth<=50)
            {
                drawArea.setFont(new Font("Cascadia Code", 0, 37));
            }
            else if(totalWidth<=100){
            drawArea.setFont(new Font("Cascadia Code", 0, 20));
        }
            drawArea.setText(str);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DrawArea.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.s = s;
    }

    public DrawArea(String s, String s2 , int totalWidth) {
        initComponents();
        if(totalWidth<=50)
            {
                drawArea.setFont(new Font("Cascadia Code", 0, 37));
            }
            else if(totalWidth<100){
            drawArea.setFont(new Font("Cascadia Code", 0, 20));
        }
        drawArea.setText(s2);
        this.s = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drawArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cascadia Code", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 31, 32));
        jLabel3.setText("Draw Area:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 32, 200, 40);

        jScrollPane1.setBorder(null);

        drawArea.setBackground(new java.awt.Color(238, 238, 238));
        drawArea.setColumns(20);
        drawArea.setFont(new java.awt.Font("Cascadia Code", 0, 11)); // NOI18N
        drawArea.setForeground(new java.awt.Color(35, 31, 32));
        drawArea.setRows(5);
        drawArea.setBorder(null);
        jScrollPane1.setViewportView(drawArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 1150, 610);

        jButton1.setBackground(new java.awt.Color(234, 192, 103));
        jButton1.setFont(new java.awt.Font("Source Code Pro SemiBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(35, 31, 32));
        jButton1.setText("Back ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1050, 30, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.s == "Draw") {
            DrawPage d = new DrawPage();
            d.setVisible(true);
            d.setLocationRelativeTo(null);
            d.pack();
            this.dispose();            
        } 
        else if (this.s == "Paper") {
            PaperPage d = new PaperPage();
            d.setVisible(true);
            d.setLocationRelativeTo(null);
            d.pack();
            this.dispose();
        }
        else {
            RoutationPage r = new RoutationPage();
            r.setVisible(true);
            r.setLocationRelativeTo(null);
            r.pack();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea drawArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
